version: '3'

services:
  client:
    build:
        context: './client'
    container_name: tom-selleck-client
    ports: 
        - '3000:3000'
    stdin_open: true
    depends_on: 
      - server
  server:
    build:
        context: ./server
    container_name: tom-selleck-server
    ports: 
        - '9000:9000'
