version: '3'

services:
  database:
    env_file:
        - database/.env.${ENVIRONMENT}
    image: byoulten/tom-selleck-database
    build:
        context: ./database
    container_name: tom-selleck-database
    ports: 
        - '27017:27017'
  index:
    env_file:
        - index/.env.${ENVIRONMENT}
    image: byoulten/tom-selleck-index
    build:
        context: ./index
    container_name: tom-selleck-index
    entrypoint:
        - bash
        - "-c"
        - "precreate-core tom_selleck_core; exec solr -f"
    ports: 
        - '8983:8983'
  daemon:
      env_file:
          - daemon/.env.${ENVIRONMENT}
      image: byoulten/tom-selleck-daemon
      build:
          context: ./daemon
      container_name: tom-selleck-daemon
      ports: 
          - '6660:6660'
      depends_on: 
          - database
          - index
  server:
    env_file:
        - server/.env.${ENVIRONMENT}
    image: byoulten/tom-selleck-server
    labels:
        kompose.service.type: NodePort
        kompose.service.nodeport.port: 32323
    build:
        context: ./server
    container_name: tom-selleck-server
    ports: 
        - '9000:9000'
    depends_on: 
        - database
        - index
  client:
    env_file:
        - client/.env.${ENVIRONMENT}
    image: byoulten/tom-selleck-client
    labels:
        kompose.service.type: NodePort
        kompose.service.nodeport.port: 31313
    build:
        context: './client'
    container_name: tom-selleck-client
    ports: 
        - '3000:3000'
    stdin_open: true
    depends_on: 
        - server

