apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployments
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: index
  name: index
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: index
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployments
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: index
    spec:
      containers:
      - command:
        - bash
        - -c
        - precreate-core tom_selleck_core; exec solr -f
        image: byoulten/tom-selleck-index
        imagePullPolicy: ""
        name: tom-selleck-index
        ports:
        - containerPort: 8983
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
